# Context Cancellation in Our own Code

```go
package main

import (
	"context"
	"fmt"
	"math/big"
	"time"
)

func calcWithTimeout(numSecond time.Duration) {
	ctx, cancelFunc := context.WithTimeout(context.Background(), numSecond*time.Second)
	defer cancelFunc()
	start := time.Now()
	result, err := calcPi(ctx)
	calcTime := time.Since(start)
	fmt.Println(result)
	fmt.Println(calcTime)
	fmt.Println(err)
}

func calcPi(ctx context.Context) (string, error) {
	var sum big.Float
	sum.SetInt64(0)
	var d big.Float
	d.SetInt64(1)
	two := big.NewFloat(2)
	i := 0
	for {
		if err := context.Cause(ctx); err != nil {
			fmt.Println("cancelled after", i, "iterations")
			return sum.Text('g', 100), err
		}
		var diff big.Float
		diff.SetInt64(4)
		diff.Quo(&diff, &d)
		if i%2 == 0 {
			sum.Add(&sum, &diff)
		} else {
			sum.Sub(&sum, &diff)
		}
		d.Add(&d, two)
		i++
	}
}

func main() {
	calcWithTimeout(1)
	calcWithTimeout(2)
	calcWithTimeout(5)
	calcWithTimeout(10)
}
```

```sh
practice ➤ make
go fmt ./...
practice.go
go vet ./...
go build
practice ➤ ./practice
cancelled after 3992964 iterations
3.1415924031492683042403324389368890479090623557567596435546875
1.000053866s
context deadline exceeded
cancelled after 7971861 iterations
3.1415927790310169917011029472320160493836738169193267822265625
2.00028579s
context deadline exceeded
cancelled after 19780507 iterations
3.14159270414461474292718012879532807346549816429615020751953125
5.001053889s
context deadline exceeded
cancelled after 39731988 iterations
3.1415926284211560287791542567248370687593705952167510986328125
10.000997862s
context deadline exceeded
```

